# bd-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bd-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bd-service
  template:
    metadata:
      labels:
        app: bd-service
    spec:
      containers:
      - name: bd-service
        image: gcr.io/annular-form-401215/bd-service:latest
        ports:
        - containerPort: 9090